// components/main/main_inference.cc
#include "tensorflow/lite/micro/all_ops_resolver.h" // if using generic resolver
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "tensorflow/lite/version.h"
#include <cstdio>
#include <cstdint>

// Extern model data generated by xxd -i (model_data.cc)
extern const unsigned char g_model[];
extern const unsigned int g_model_len;

using namespace tflite;

// Example tensor arena size — start large and then reduce as experiment.
// Start with 40KB (adjust down for bonus experiment). If your model is larger, raise it.
constexpr int kTensorArenaSize = 40 * 1024;
static uint8_t tensor_arena[kTensorArenaSize];

// Setup model and interpreter — integrate with your app_main / task
void setup_and_run_model_once()
{
    const Model* model = GetModel(g_model);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        printf("Model schema version mismatch\n");
        return;
    }

    // Use MicroMutableOpResolver with only ops we need (3 in this example)
    static MicroMutableOpResolver<3> resolver;
    if (resolver.AddFullyConnected() != kTfLiteOk) { printf("AddFullyConnected failed\n"); return; }
    if (resolver.AddQuantize() != kTfLiteOk) { printf("AddQuantize failed\n"); return; }
    if (resolver.AddDequantize() != kTfLiteOk) { printf("AddDequantize failed\n"); return; }

    static MicroInterpreter interpreter(model, resolver, tensor_arena, kTensorArenaSize);
    TfLiteStatus allocate_status = interpreter.AllocateTensors();
    if (allocate_status != kTfLiteOk) {
        printf("AllocateTensors() failed\n");
        return;
    }

    // Bonus tip: print arena usage
    size_t used_bytes = interpreter.arena_used_bytes();
    printf("Tensor arena used bytes: %u / %d\n", (unsigned)used_bytes, kTensorArenaSize);

    // Example: fill input then invoke — replace with your inference loop
    TfLiteTensor* input = interpreter.input(0);
    // populate input->data.int8[...] according to your quantization
    // For demonstration set zero
    if (input->type == kTfLiteInt8) {
        for (int i = 0; i < input->bytes; ++i) {
            input->data.int8[i] = 0;
        }
    }

    TfLiteStatus invoke_status = interpreter.Invoke();
    if (invoke_status != kTfLiteOk) {
        printf("Invoke failed\n");
        return;
    }

    TfLiteTensor* output = interpreter.output(0);
    // read output (depending on type)
    float y_value = 0.0f;
    if (output->type == kTfLiteInt8) {
        // for int8, dequantize manually: real = (val - zero_point) * scale
        int8_t q = output->data.int8[0]; // if output is 1-element
        float scale = output->params.scale;
        int32_t zero_point = output->params.zero_point;
        y_value = (q - zero_point) * scale;
    } else if (output->type == kTfLiteFloat32) {
        y_value = output->data.f[0];
    }

    // Example x_value (if your model needs it)
    float x_value = 0.0f;

    // Call the LVGL display handler defined earlier
    extern void HandleOutput(float x_value, float y_value);
    HandleOutput(x_value, y_value);
}
